
import { CONFIG } from '../config';

export interface OrderDetails {
  id: string;
  items: { name: string; price: number; quantity: number }[];
  total: number;
  customerName: string;
  customerPhone: string;
  paymentMethod: string;
}

export const generateWhatsAppOrderLink = (order: OrderDetails): string => {
  const itemsText = order.items
    .map(item => `${item.quantity}x ${item.name} (R${item.price})`)
    .join('\n');

  const message = `🚀 *NEW ORDER RECEIVED!*
*Order ID:* #${order.id}
--------------------------
*Items:*
${itemsText}

*Total:* R${order.total.toFixed(2)}
*Status:* ✅ PAID (${order.paymentMethod})
--------------------------
*Customer:* ${order.customerName}
*Phone:* ${order.customerPhone}

_Generated by GreenNova AI_`;

  return `https://wa.me/${CONFIG.contact.whatsappNumber}?text=${encodeURIComponent(message)}`;
};
